"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.0.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
import os
from django.urls import reverse_lazy


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

DOMAIN = "http://localhost:8000"


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-m=h8!7z$#-un2falajymaodxmp)+n14tz_9z9kknl(@0(c0uyt"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]

BASE_URL = "http://localhost:8000"

# Application definition
USER = [
    "apps.ecommerce",
    "apps.home",
    "apps.user",
]

THIRD_PARTY = [
    "django_extensions",
    "crispy_forms",
    "crispy_tailwind",
    "django_htmx",
    "widget_tweaks",
    "active_link",
    "template_partials",
]

TENANT = [
    "apps.tenant",
]

CRISPY_ALLOWED_TEMPLATE_PACKS = "tailwind"
CRISPY_TEMPLATE_PACK = "tailwind"

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.humanize",
]

INSTALLED_APPS += USER
INSTALLED_APPS += TENANT
INSTALLED_APPS += THIRD_PARTY

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    # "core.middleware.ecommerce.CustomLoginRequiredMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "django_htmx.middleware.HtmxMiddleware",
]

CUSTOM_MIDDLEWARE = [
    "core.middleware.ecommerce.CheckIfTenantExists",
    "core.middleware.ecommerce.TenantMiddleware",
    "core.middleware.ecommerce.CustomerMiddleware",
]

MIDDLEWARE += CUSTOM_MIDDLEWARE

ROOT_URLCONF = "core.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "core/templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "core.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = "/static/"
STATIC_ROOT = os.path.join(BASE_DIR, "static/")

MEDIA_ROOT = os.path.join(BASE_DIR, "data/")  # 'data' is my media folder
MEDIA_URL = "/media/"


DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

AUTH_USER_MODEL = "user.CustomUser"


TENANT_LOGIN_REDIRECT = reverse_lazy("pasal-dashboard")


AUTHENTICATION_BACKENDS = [
    "django.contrib.auth.backends.ModelBackend",  # Keep the default ModelBackend for other authentication methods
    "apps.tenant.auth.CustomTenantAuthBackend",
]

X_FRAME_OPTIONS = "ALLOW-FROM *.localhost:8000/"


STRIPE_PUBLIC_KEY = "pk_test_51OGk1UF9yXfHu69QYEujtrjmzFmfQH8rYmYehFjNM1hHFKbDC1Q3cN3z5XfSbwoizfT7IV1yX7HObYIwztE3X48i00azNAiRmP"
STRIPE_SECRET_KEY = "sk_test_51OGk1UF9yXfHu69Q4rk3IVOokSgDaAR8xuMGONup3Fu3CRUV8YGxD2Resc2QRksVIXNaCiptdNroNkBYZGRc6Bi4006RxCZihg"
STRIPE_WEBHOOK_SECRET = (
    "whsec_5ef1981094cdc962402e736b7fae149f90a02d1ba9aa5661089f90a1b4945266"
)


# ACTIVE_LINK_CSS_CLASS = "bg-gray-300"
